sonar.organization=ntrix
sonar.projectKey=ntrix_amazin

sonar.sources=apps/amazin/src
sonar.exclusions=apps/amazin/src/__tests__/**,apps/amazin/src/stories/**

sonar.tests=apps/amazin/src/__tests__
sonar.test.inclusions=apps/amazin/src/__tests__/**

sonar.javascript.lcov.reportPaths=apps/amazin/coverage/lcov.info
